class Headlamp : Inventory
{
    Default
    {
        +COUNTITEM;
        +INVENTORY.HUBPOWER;
        +INVENTORY.PERSISTENTPOWER;
        +INVENTORY.IGNORESKILL;
        +DONTGIB;
        //+INVENTORY.INVBAR;
        Inventory.InterHubAmount 1;
        Inventory.MaxAmount 1;
        Inventory.PickupSound "misc/gettool" ;
	    Inventory.PickupMessage "Picked up a headlamp.";
	    +INVENTORY.ALWAYSPICKUP;
	}
}
